CCFLAGS = -Wall -Werror -Wextra -pedantic 

all: solution_pt1 solution_pt2

solution_pt1: solution_pt1.cpp
	g++ $(CCFLAGS) solution_pt1.cpp -o solution_pt1 

solution_pt2: solution_pt2.cpp 
	g++ $(CCFLAGS) solution_pt2.cpp -o solution_pt2 
